.TH READ 2
.SH NAME
read \- read from a file descriptor
.SH SYNOPSIS
.nf
#include <unistd.h>

ssize_t read(int fd, void *buf, size_t len);
.fi
.SH DESCRIPTION
The
.B read()
function attempts to read
.I len
bytes from the object referenced by the file descriptor
.I fd
into the buffer pointed to by
.I buf.
.SH RETURN VALUES
Upon successful completion, the number of bytes read is returned.
A return value of 0 indicates end-of-file.
On error, \-1 is returned.
.SH SEE ALSO
write(2),
lseek(2)
